# : Manager {{{

[manager]
cwd = { fg = "#8bd5ca" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#eed49f", bold = true, italic = true, underline = true }
find_position = { fg = "#f5bde6", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#a6da95", bg = "#a6da95" }
marker_cut      = { fg = "#ed8796", bg = "#ed8796" }
marker_marked   = { fg = "#8bd5ca", bg = "#8bd5ca" }
marker_selected = { fg = "#eed49f", bg = "#eed49f" }

# Tab
tab_active   = { reversed = true }
tab_inactive = {}
tab_width    = 1

# Count

count_copied   = { fg = "#24273a", bg = "#a6da95" }
count_cut      = { fg = "#24273a", bg = "#ed8796" }
count_selected = { fg = "#24273a", bg = "#eed49f" }

# Border
border_symbol = "│"
border_style  = { fg = "#8087a2" }

# : }}}


# : Mode {{{

[mode]

normal_main = { fg = "#24273a", bg = "#8aadf4", bold = true }
normal_alt  = { fg = "#8aadf4", bg = "#363a4f" }

# Select mode
select_main = { fg = "#24273a", bg = "#8bd5ca", bold = true }
select_alt  = { fg = "#8bd5ca", bg = "#363a4f" }

# Unset mode
unset_main = { fg = "#24273a", bg = "#f0c6c6", bold = true }
unset_alt  = { fg = "#f0c6c6", bg = "#363a4f" }
# : }}}


# : Status bar {{{

[status]
separator_open  = ""
separator_close = ""

# Progress

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8aadf4", bg = "#494d64" }
progress_error  = { fg = "#ed8796", bg = "#494d64" }

# Permissions

perm_sep   = { fg = "#8087a2" }
perm_type  = { fg = "#8aadf4" }
perm_read  = { fg = "#eed49f" }
perm_write = { fg = "#ed8796" }
perm_exec  = { fg = "#a6da95" }

# : }}}


# : Pick {{{

[pick]
border   = { fg = "#8aadf4" }
active   = { fg = "#f5bde6", bold = true }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#8aadf4" }
title    = {}
value    = {}
selected = { reversed = true }
# : }}}


# : Completion {{{

[completion]
border = { fg = "#8aadf4" }
# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#8aadf4" }
title   = {}
hovered = { fg = "#f5bde6", underline = true }
# : }}}


# : Which {{{

[which]
mask            = { bg = "#363a4f" }
cand            = { fg = "#8bd5ca" }
rest            = { fg = "#939ab7" }
desc            = { fg = "#f5bde6" }
separator       = "  "
separator_style = { fg = "#5b6078" }
# : }}}


# : Help {{{

[help]
on      = { fg = "#8bd5ca" }
run     = { fg = "#f5bde6" }
hovered = { reversed = true, bold = true }
footer  = { fg = "#363a4f", bg = "#cad3f5" }

# : }}}


# : Notify {{{

[notify]
title_info  = { fg = "#a6d189" }
title_warn  = { fg = "#e5c890" }
title_error = { fg = "#e78284" }

# : }}}

# : Icons {{{
[icon]
prepend_dirs = [
	{ name = "Desktop", text = "󰟀" },
        { name = "Downloads", text = "" },
        { name = "Documents", text = "󱔗" },
        { name = "Pictures", text = "󰋯" },
        { name = "Public", text = "" },
        { name = "Music", text = "󰌳" },
        { name = "Videos", text = "󰨜" },

	# ...
]
append_exts = [
	{ name = "conf", text = "" },
	{ name = "sh", text = "" },
	{ name = "png", text = "" },
	{ name = "jpg", text = "" },
	{ name = "jpeg", text = "" },
	{ name = "svg", text = "" },
	{ name = "pdf", text = "" },
	{ name = "md", text = "󰍔" },
	{ name = "key", text = "" },
	{ name = "pub", text = "" },
	{ name = "psk", text = "" },
        { name = "html", text = "", fg = "#ff6600"},
]

exts = [
	{ name = "mp3", text = "" },
	{ name = "desktop", text = "󰟀" },
	{ name = "bak", text = "󰁯" },
	{ name = "c", text = "", fg = "#03A9F4" },
	{ name = "asm", text = "" },
	{ name = "rs", text = "󱘗", fg = "#b7410e" },
	# ...
]

prepend_conds = [
        { if = "hidden & dir",  text = "󰊠", fg = "#aaa1a2" },  # Hidden directories
	{ if = "dir",           text = "" },  # Directories
	{ if = "link",          text = "󰌹 " },  # Link
	{ if = "exec", text = " " },  # Normal files (not directories or symlinks)
	{ if = "!(dir | link)", text = "󰈔" },  # Normal files (not directories or symlinks)
]


# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#81c8be" },

	# Media
	{ mime = "{audio,video}/*", fg = "#e5c890" },
        
        # Exec
        { mime = "*/pie-executable", fg = "#4ff4cb"},

	# Archives
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f4b8e4" },

	# Documents
	{ mime = "application/{pdf,doc,rtf}", fg = "#a6d189" },

        # Orphan symbolic links
        { name = "*", is = "orphan", fg = "#ed2939" },

	# Fallback
	{ name = "*", fg = "#c6d0f5" },
	{ name = "*/", fg = "#8caaee" }
]

# : }}}
