[manager]
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
linemode = "mtime"
title_format = "yazi: {cwd}"
image_filter = "lanczos3"
image_quality = 40
ratio = [1, 3, 4]
[preview]
wrap = "yes"

[opener]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open" },
]
pdf_open = [
        { run = 'evince "$@"', orphan = true, desc = "Open" },

]
image_open = [
        { run = 'imv "$@"', orphan = true, desc = "Oepn" },
]

[open]
prepend_rules = [
	{ name = "*.json", use = "edit" },
	{ name = "*.html", use = [ "edit", "open"] },
	{ name = "*.pdf", use = "pdf_open" },
	{ name = "*.png", use = "image_open" },
	{ name = "*.jpg", use = "image_open" },
	{ name = "*.svg", use = "image_open" },
        { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
]
append_rules = [
	{ name = "*", use = "open" },
]

[plugin]
prepend_previewers = [
        { mime = "image/{avif,heic,jxl,svg+xml}", run = "magick" }, 
	# { mime = "image/*", run = "image" },
]


[input]
cursor_blink = true
origin = "center"

[pick]
open = true


